import sys

C=int(sys.argv[1])

SHL_6 = C << 6
SHL_5 = C << 5
SHL_2 = C << 2
SHL_1 = C << 1

SUM_TOP_LEFT = SHL_6 + SHL_5
SUM_TOP_RIGHT = SHL_2 + SHL_1

SUM_MIDDLE = SUM_TOP_LEFT + SUM_TOP_RIGHT

SHR_7 = SUM_MIDDLE >> 7
SUM_BOTTOM_LEFT = C + SHR_7
SUM_BOTTOM = SUM_BOTTOM_LEFT + 32

F = SUM_BOTTOM
print(F)
